### ISSUE TITLE
automatic folder listing

### ISSUE THREAD

**Issue by tamscenterdata** [tamscenter/tamscenter.github.io#1]
it would be great if we had automatically drop down list for each folder @nowfred

**Comment by lllleonnnn** [comment]
ok @melindadataqueen - i will look into it

**Comment by tamscenterdata** [comment]
aoeu

**Comment by lllleonnnn** [comment]
Hey - DEFINITELY do not respond with shit like that to emails from github -
your entire response was pasted in a public page

BE careful!
